name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Write GCP keyfile
        run: |
          echo "${{ secrets.GCP_KEY }}" > $HOME/gcp-key.json

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
nyc_taxi_analysis:
  target: "dev"
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: ${{ secrets.GCP_PROJECT_ID }}
      dataset: dev
      keyfile: $HOME/gcp-key.json
      threads: 4
    prod:
      type: bigquery
      method: service-account
      project: ${{ secrets.GCP_PROJECT_ID }}
      dataset: prod
      keyfile: $HOME/gcp-key.json
      threads: 4
EOF

      - name: dbt debug
        run: dbt debug --profiles-dir ~/.dbt

      - name: dbt deps
        run: dbt deps --profiles-dir ~/.dbt

      - name: dbt seed
        run: dbt seed --profiles-dir ~/.dbt

      - name: dbt run
        run: dbt run --profiles-dir ~/.dbt

      - name: dbt test
        run: dbt test --profiles-dir ~/.dbt
