name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt and adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Configure dbt profiles
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
my_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ${{ secrets.GCP_PROJECT_ID }}
      dataset: dev
      threads: 4
EOF

      - name: dbt debug
        run: dbt debug --profiles-dir ~/.dbt

      - name: dbt deps
        run: dbt deps --profiles-dir ~/.dbt

      - name: dbt run
        run: dbt run --profiles-dir ~/.dbt

      - name: dbt test
        run: dbt test --profiles-dir ~/.dbt
