name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - uses: actions/checkout@v4

      # 2. Authenticate to GCP
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      # 3. Set up Python & install dbt + adapter
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      # 4. Configure your profiles.yml
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          nyc_taxi_analysis:
            target: "${{ secrets.DBT_TARGET || 'dev' }}"
            outputs:
              dev:
                type: bigquery
                project: ${{ secrets.GCP_PROJECT_ID }}
                dataset: dev
                keyfile_json: "${{ secrets.GCP_KEY }}"
                threads: 4
              prod:
                type: bigquery
                project: ${{ secrets.GCP_PROJECT_ID }}
                dataset: prod
                keyfile_json: "${{ secrets.GCP_KEY }}"
                threads: 4
          EOF

      # 5. Run dbt commands
      - name: dbt deps
        run: dbt deps

      - name: dbt seed
        run: dbt seed --profiles-dir ~/.dbt

      - name: dbt run
        run: dbt run --profiles-dir ~/.dbt

      - name: dbt test
        run: dbt test --profiles-dir ~/.dbt
